// POST /api/compare
// Claude compares multiple AI-generated images and provides insight

import Anthropic from '@anthropic-ai/sdk';
import {
  handleCors, errorResponse, requireAuth, readJson,
  parseDataUrl, envMiddleware,
} from './_lib/utils.js';

export default async function handler(req, res) {
  if (handleCors(req, res)) return;
  if (req.method !== 'POST') return errorResponse(res, 405, 'method_not_allowed', 'POST only');
  if (!envMiddleware(res, ['ANTHROPIC_API_KEY'])) return;

  try { await requireAuth(req); }
  catch (err) { return errorResponse(res, err.status || 401, 'unauthorized', err.message); }

  try {
    const { prompt, results = [], language = 'ko' } = await readJson(req);
    if (!results.length) return errorResponse(res, 400, 'missing_results', 'results array required');
    if (results.length < 2) return res.status(200).json({ analysis: null, skipped: true });

    const client = new Anthropic({ apiKey: process.env.ANTHROPIC_API_KEY });

    const langInstruction = language === 'en'
      ? 'Respond in English, 2-3 sentences.'
      : '한국어로 2-3문장으로 답하세요.';

    const systemPrompt = `You are a fashion image quality analyst. Given a prompt and multiple AI-generated images from different models, briefly compare them and offer insight on which model handled this type of prompt best, and why.

${langInstruction}
- Name each model's strength (garment fidelity, lighting, composition, realism)
- Recommend which is best for this prompt type
- Do not be verbose`;

    const userContent = [
      { type: 'text', text: `Prompt: "${prompt}"\n\nImages generated by different models:` },
    ];

    for (const r of results) {
      userContent.push({
        type: 'text',
        text: `\n--- ${r.modelName || r.modelKey} (${r.modelKey}) ---`,
      });
      const parsed = parseDataUrl(r.imageUrl);
      if (parsed) {
        userContent.push({
          type: 'image',
          source: { type: 'base64', media_type: parsed.mimeType, data: parsed.data },
        });
      } else if (r.imageUrl && r.imageUrl.startsWith('http')) {
        userContent.push({
          type: 'image',
          source: { type: 'url', url: r.imageUrl },
        });
      }
    }

    const msg = await client.messages.create({
      model: 'claude-haiku-4-5',
      max_tokens: 400,
      system: systemPrompt,
      messages: [{ role: 'user', content: userContent }],
    });

    const analysis = msg.content
      .filter(b => b.type === 'text')
      .map(b => b.text)
      .join('')
      .trim();

    return res.status(200).json({ analysis });

  } catch (err) {
    console.error('[compare]', err);
    return errorResponse(res, 500, 'compare_failed', 'Comparison failed', err.message);
  }
}
